name: scicookie
channels:
  - nodefaults
  - conda-forge
dependencies:
  - bash
  - git
  - opensciencelabs::circleci-cli
  - python >=3.9,<3.12
  - poetry >=2
  - nodejs
  - compilers
  - pip
  - pip:
      - makim==1.20.0
      - paginate==0.5.6
